


name: .NET Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.8.x'

    - name: Restore dependencies
      run: dotnet restore src/Pkcs11Admin.sln

    - name: Build
      run: dotnet build src/Pkcs11Admin.sln --configuration ${{ matrix.configuration }}

    - name: Run tests
      run: dotnet test src/Pkcs11Admin.Tests --configuration ${{ matrix.configuration }} --no-build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Pkcs11Admin-${{ matrix.configuration }}
        path: |
          src/Pkcs11Admin.WinForms/bin/${{ matrix.configuration }}/
          src/Pkcs11Admin/bin/${{ matrix.configuration }}/

